version: '3.5'
services:
  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: homeassistant/aarch64-hassio-audio #ghcr.io/home-assistant/home-assistant:2022.11.5
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config

#########################################################
#version: '3'
#services:
#  homeassistant:
#    container_name: homeassistant
#    image: "ghcr.io/home-assistant/home-assistant:stable"
#    volumes:
#      - ./config:/config
#      - /etc/localtime:/etc/localtime:ro
#    restart: unless-stopped
#    privileged: true
#    network_mode: host

#####################################################

#version: '3'
#services:
#  homeassistant:
#    container_name: homeassistant-test
#    hostname: homeassistant-test
#    image: homeassistant/home-assistant:stable
#    restart: unless-stopped
#    privileged: true
#    networks:
#      backend:
#        ipv4_address: 10.10.0.99
#    environment:
#      DISABLE_JEMALLOC: true
#      TZ: America/Fortaleza
#networks:
#  backend:
#    name: backend
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 10.10.0.0/24
#          gateway: 10.10.0.1
#
#######################################################
#version: '3'
#services:
#  homeassistant:
#    container_name: homeassistant
#    image: "ghcr.io/home-assistant/home-assistant:stable"
#    volumes:
#      - ./Home-Assistant/config:/config
#      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "8123:8123"
#    restart: unless-stopped
#    privileged: true
#    network_mode: host
##########################################################
#version: '3'
#services:
#  homeassistant:
#    container_name: hass
#    image: homeassistant/home-assistant
#    volumes:
#      - ./hass-config:/config
#      - /etc/localtime:/etc/localtime:ro
#    restart: unless-stopped
#    network_mode: host
#    depends_on:
#      - mariadb
#      - mosquitto
#  mariadb:
#    image: linuxserver/mariadb
#    container_name: mariadb
#    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: homeassistant
#      MYSQL_DATABASE: ha_db
#      MYSQL_USER: homeassistant
#      MYSQL_PASSWORD: homeassistant
#      PUID: 1000
#      PGID: 1000
#    volumes:
#      - ./mariadb:/config
#    ports:
#      - "3306:3306"
#  nodered:
#    container_name: nodered
#    image: nodered/node-red
#    ports:
#      - "1880:1880"
#    volumes:
#      - ./nodered:/data
#    depends_on:
#      - homeassistant
#      - mosquitto
#    environment:
#      TZ: "America/Fortaleza"
#    restart: unless-stopped
#  mosquitto:
#    image: eclipse-mosquitto
#    container_name: mosquitto
#    restart: unless-stopped
#    ports:
#      - "1883:1883"
#    volumes:
#      - "./mosquitto/config:/mosquitto/config"
#      - "./mosquitto/data:/mosquitto/data"
#      - "./mosquitto/log:/mosquitto/log"
#    environment:
#      - TZ=America/Fortaleza
#    user: "${PUID}:${PGID}"
#  hass-configurator:
#    image: "causticlab/hass-configurator-docker:arm"
#    container_name: hass-configurator
#    restart: unless-stopped
#    ports:
#      - "3218:3218/tcp"
#    depends_on:
#      - homeassistant
#    volumes:
#      - "./configurator-config:/config"
#      - "./hass-config:/hass-config"
#    user: "${PUID}:${PGID}"

